### ISSUE TITLE
Plugin working, but i'm getting error

### ISSUE THREAD

**Issue by criskkky** [Franc1sco/CS2-Parachute#7]
Plugin work fine, but what is this error related to?
```
16:38:34 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '65280' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Parachute.Parachute.<Load>b__14_3() in D:\GitHub\CS2-Parachute\src\Parachute.cs:line 116
   at InvokeStub_OnTick.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass45_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 357
   at InvokeStub_Action`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

**Comment by lostsoul6** [comment]
@criskkky Hello there , since you are using this plugin , can I kindly ask you to check and see if you have the problem mentioned in topic below?

https://github.com/Franc1sco/CS2-Parachute/issues/8

Every time I press E to use parachute in the server , an Error is printed in the console which I sent in the picture . Would really appreciate it if you could check it .

**Comment by criskkky** [comment]
Hi @lostsoul6, same for me

**Comment by lostsoul6** [comment]
@criskkky do you also have the problem that the parachute sometimes opens and sometimes doesn't? It looks bad in the game . 

Regarding the errors in console , I don't know if they are warnings or critical errors . If they are just warnings , I wish the developer can hide them because they populate the console and are annoying .

**Comment by Franc1sco** [comment]
Fixed in the latest version.
